# Generated by Django 4.0 on 2021-12-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realestate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=5)),
                ('realestate_area', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('land_area', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
    ]
