# Generated by Django 4.0 on 2021-12-09 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, null=True, verbose_name='Street')),
                ('street_number', models.CharField(max_length=10, null=True, verbose_name='Street number')),
                ('apartment_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Apartment number')),
                ('zip_code', models.CharField(max_length=10, null=True, verbose_name='ZIP Code')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_price', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Plot price')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Total area')),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='realestates.address', verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Realestate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realestate_type', models.IntegerField(choices=[(0, 'Multi-family'), (1, 'Single-family')], null=True, verbose_name='Realestete type')),
                ('realestate_price', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Realestete price')),
                ('realestate_area', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Realestete area')),
                ('number_floors', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Number floors')),
                ('plot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realestates.plot', verbose_name='Plot')),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garage_type', models.IntegerField(choices=[(0, 'No'), (1, 'Underground'), (2, 'External'), (3, 'Detached'), (4, 'Belonging')], null=True, verbose_name='Garage type')),
                ('garage_price', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Garage price')),
                ('realestate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realestates.realestate')),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_price', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Flat price')),
                ('flat_area', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Flat area')),
                ('floor_number', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Floor number')),
                ('realestate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realestates.realestate', verbose_name='Realestate')),
            ],
        ),
    ]
