# Generated by Django 4.0 on 2021-12-09 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('street_number', models.CharField(blank=True, max_length=10, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='land_area',
        ),
        migrations.AlterField(
            model_name='realestate',
            name='realestate_area',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='type',
            field=models.CharField(choices=[('HOUSE', 'house'), ('FLAT', 'flat')], max_length=5),
        ),
        migrations.AddField(
            model_name='realestate',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realestates.address'),
        ),
    ]
