# Generated by Django 4.0 on 2021-12-09 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='realestate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realestates.realestate', verbose_name='Realestate'),
        ),
    ]
