# Generated by Django 4.0 on 2022-02-15 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='plot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realestates.plot', verbose_name='Plot address'),
        ),
    ]
