# Generated by Django 4.0 on 2021-12-09 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0002_alter_garage_realestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realestates.address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='plot_price',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Plot price'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='total_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Total area'),
        ),
    ]
