# Generated by Django 4.0 on 2022-02-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0003_remove_realestate_area'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('street', 'street_number', 'zip_code', 'city')},
        ),
    ]
