# Generated by Django 4.0 on 2021-12-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0003_alter_address_street_alter_address_street_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
