# Generated by Django 4.0 on 2022-02-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0004_alter_address_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('street', 'street_number', 'city')},
        ),
    ]
