# Generated by Django 4.0 on 2021-12-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0004_address_apartment_number_alter_address_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='realestate_area',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
