# Generated by Django 4.0 on 2021-12-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0005_alter_realestate_realestate_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realestate',
            old_name='realestate_area',
            new_name='area',
        ),
        migrations.AddField(
            model_name='realestate',
            name='area_land',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='bathroom',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='kitchen',
            field=models.CharField(blank=True, choices=[('OPEN', 'open'), ('CLOSED', 'closed')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='rooms',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='year_built',
            field=models.DateField(blank=True, null=True),
        ),
    ]
