# Generated by Django 4.0 on 2022-02-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0005_alter_address_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('name', 'surname', 'email')},
        ),
    ]
