# Generated by Django 4.0 on 2021-12-09 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0005_alter_plot_plot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='realestates.address', verbose_name='Address'),
        ),
    ]
