# Generated by Django 4.0 on 2022-02-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0006_alter_client_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('name', 'surname', 'email', 'mobile_number')},
        ),
    ]
