# Generated by Django 4.0 on 2021-12-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0006_rename_realestate_area_realestate_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='all_floors',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='floor_number',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
