# Generated by Django 4.0 on 2021-12-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0006_alter_plot_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='realestate_type',
            field=models.IntegerField(choices=[(0, 'Multi-family house'), (1, 'Single-family house')], null=True, verbose_name='Realestete type'),
        ),
    ]
