# Generated by Django 4.0 on 2021-12-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0007_realestate_all_floors_realestate_floor_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='garage',
            field=models.CharField(blank=True, choices=[('YES', 'yes'), ('NO', 'no')], max_length=3, null=True),
        ),
    ]
