# Generated by Django 4.0 on 2022-02-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0007_alter_client_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plot',
            old_name='type',
            new_name='type_plot',
        ),
    ]
