# Generated by Django 4.0 on 2021-12-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0008_realestate_garage'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
