# Generated by Django 4.0 on 2022-02-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0008_rename_type_plot_type_plot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plot',
            old_name='total_area',
            new_name='total_area_plot',
        ),
    ]
