# Generated by Django 4.0 on 2021-12-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0008_remove_flat_flat_area_remove_flat_flat_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='balcon_type',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Balcon'), (2, 'Loggia'), (3, 'Terrace')], default=0, null=True, verbose_name='Balkon type'),
        ),
    ]
