# Generated by Django 4.0 on 2022-02-21 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0009_rename_total_area_plot_total_area_plot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='description',
        ),
    ]
