# Generated by Django 4.0 on 2021-12-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0009_realestate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='city',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
