# Generated by Django 4.0 on 2021-12-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0011_flat_house_delete_realestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city_district',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
