# Generated by Django 4.0 on 2021-12-10 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0012_alter_address_city_alter_address_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='balcon_type',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Balcony'), (2, 'Loggia'), (3, 'Terrace')], default=0, verbose_name='Balkony type'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor_number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Floor number'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='realestate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestates.realestate', verbose_name='Realestate'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='garage_price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Garage price'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='garage_type',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Underground'), (2, 'External'), (3, 'Detached'), (4, 'Belonging')], verbose_name='Garage type'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='realestate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestates.realestate', verbose_name='Realestate'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realestates.address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='total_area',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Total area'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='bathroom',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Bathroom'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='kitchen',
            field=models.IntegerField(choices=[(0, 'Kitchen open'), (1, 'Kitchen closed')], verbose_name='Kitchen'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='number_floors',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number floors'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestates.plot', verbose_name='Plot'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='realestate_area',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Realestete area'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='realestate_price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Realestete price'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='realestate_type',
            field=models.IntegerField(choices=[(0, 'Multi-family house'), (1, 'Single-family house')], verbose_name='Realestete type'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='rooms',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Rooms'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='year_built',
            field=models.DateField(verbose_name='Year built'),
        ),
    ]
