# Generated by Django 4.0 on 2021-12-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0012_address_city_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='area_land',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
