# Generated by Django 4.0 on 2021-12-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0013_alter_flat_balcon_type_alter_flat_floor_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='apartment_number',
        ),
        migrations.AddField(
            model_name='flat',
            name='apartment_number',
            field=models.CharField(max_length=10, null=True, verbose_name='Apartment number'),
        ),
    ]
