# Generated by Django 4.0 on 2021-12-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0014_remove_address_apartment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='apartment_number',
            field=models.CharField(max_length=10, verbose_name='Apartment number'),
        ),
    ]
