# Generated by Django 4.0 on 2021-12-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0015_alter_flat_apartment_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Sale'), (1, 'Lease')], verbose_name='Offer type')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.RenameField(
            model_name='plot',
            old_name='plot_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='base',
            old_name='realestate_area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='base',
            old_name='kitchen',
            new_name='kitchen_type',
        ),
        migrations.RenameField(
            model_name='base',
            old_name='realestate_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='balcon_type',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='garage_price',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='garage_type',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='plot_price',
        ),
        migrations.RemoveField(
            model_name='base',
            name='description',
        ),
        migrations.RemoveField(
            model_name='base',
            name='realestate_price',
        ),
        migrations.AddField(
            model_name='flat',
            name='balcony_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Balcony'), (1, 'Loggia'), (2, 'Terrace')], null=True, verbose_name='Balkony type'),
        ),
        migrations.AddField(
            model_name='garage',
            name='type',
            field=models.IntegerField(choices=[(0, 'Underground'), (1, 'External'), (2, 'Detached'), (3, 'Belonging')], default=0, verbose_name='Garage type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor_number',
            field=models.PositiveSmallIntegerField(verbose_name='Floor number'),
        ),
        migrations.AlterField(
            model_name='base',
            name='bathroom',
            field=models.PositiveSmallIntegerField(verbose_name='Bathroom'),
        ),
        migrations.AlterField(
            model_name='base',
            name='number_floors',
            field=models.PositiveSmallIntegerField(verbose_name='Number floors'),
        ),
        migrations.AlterField(
            model_name='base',
            name='rooms',
            field=models.PositiveSmallIntegerField(verbose_name='Rooms'),
        ),
    ]
