# Generated by Django 4.0 on 2021-12-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0019_alter_realestate_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='parking_number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Parking space number'),
            preserve_default=False,
        ),
    ]
