# Generated by Django 4.0 on 2021-12-11 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0021_alter_flat_balcony_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='balcony_type',
            field=models.IntegerField(choices=[(0, 'Balcony'), (1, 'Loggia'), (2, 'Terrace')], null=True, verbose_name='Balcony type'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='bathroom',
            field=models.PositiveSmallIntegerField(verbose_name='Number of bathroom'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='kitchen_type',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')], verbose_name='Kitchen type'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='rooms',
            field=models.PositiveSmallIntegerField(verbose_name='Number of rooms'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realestates.address', verbose_name='Plot address'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='total_area',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Total plot area'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Total realestete area'),
        ),
    ]
