# Generated by Django 4.0 on 2021-12-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0023_alter_plot_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
    ]
