# Generated by Django 4.0 on 2021-12-27 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0024_alter_address_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realestates.address', verbose_name='Plot address'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='total_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Total plot area'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='type',
            field=models.IntegerField(choices=[(0, 'Building plot'), (1, 'Agricultural plot'), (2, 'Investment plot')], verbose_name='Plot type'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Total realestete area'),
        ),
    ]
