# Generated by Django 4.0 on 2021-12-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0025_alter_plot_address_alter_plot_total_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='area',
            field=models.DecimalField(decimal_places=2, default='67', max_digits=7, verbose_name='Total realestete area'),
        ),
    ]
