# Generated by Django 4.0 on 2021-12-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0026_flat_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='area',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=7, verbose_name='Total realestete area'),
        ),
    ]
