# Generated by Django 4.0 on 2021-12-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0027_alter_flat_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Apartment number'),
        ),
    ]
