# Generated by Django 4.0 on 2021-12-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0028_alter_flat_apartment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='type',
            field=models.IntegerField(choices=[(0, 'Underground'), (1, 'External parking space'), (2, 'Detached'), (3, 'Attached')], verbose_name='Garage type'),
        ),
    ]
