# Generated by Django 4.0 on 2021-12-27 20:40

from django.db import migrations, models
import gfklookupwidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('realestates', '0029_alter_garage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='type',
            field=models.IntegerField(choices=[(0, 'Underground'), (1, 'External space'), (2, 'Detached'), (3, 'Attached')], verbose_name='Garage type'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='object_id',
            field=gfklookupwidget.fields.GfkLookupField(),
        ),
    ]
