version: "3"
services:
  backend:
    build: .
    ports:
      - "7000:8080"
    depends_on:
      - database

  database:
    image: postgres:13.1
    env_file:
      - .env
    volumes:
      - "dane:/var/lib/postgresql/data"

volumes:
  dane:
